"""water readings  allocation fields

Revision ID: 18329a4bdad6
Revises: da74a98e4c6a
Create Date: 2026-02-09 22:05:40.984666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18329a4bdad6'
down_revision = 'da74a98e4c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('reading_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reading_at', sa.DateTime(), nullable=False),
    sa.Column('prev_reading_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('usage_units', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rate_per_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('water_readings', schema=None) as batch_op:
        batch_op.create_index('ix_water_readings_reading_at', ['reading_at'], unique=False)
        batch_op.create_index('ix_water_readings_tenant', ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_water_readings_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_water_readings_unit', ['unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_water_readings_unit_id'), ['unit_id'], unique=False)
        batch_op.create_index('ix_water_readings_unit_reading_at', ['unit_id', 'reading_at'], unique=False)

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('water_rate_per_unit', sa.Numeric(precision=12, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('water_rate_per_unit')

    with op.batch_alter_table('water_readings', schema=None) as batch_op:
        batch_op.drop_index('ix_water_readings_unit_reading_at')
        batch_op.drop_index(batch_op.f('ix_water_readings_unit_id'))
        batch_op.drop_index('ix_water_readings_unit')
        batch_op.drop_index(batch_op.f('ix_water_readings_tenant_id'))
        batch_op.drop_index('ix_water_readings_tenant')
        batch_op.drop_index('ix_water_readings_reading_at')

    op.drop_table('water_readings')
    # ### end Alembic commands ###
