"""add indexes and unique constraints

Revision ID: 64c798f5c3ca
Revises: 7a170a131005
Create Date: 2026-01-28 15:04:54.539624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64c798f5c3ca'
down_revision = '7a170a131005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lease', schema=None) as batch_op:
        batch_op.create_index('ix_lease_is_active', ['is_active'], unique=False)

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.create_index('ix_property_location', ['location'], unique=False)
        batch_op.create_index('ix_property_name', ['name'], unique=False)

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.create_index('ix_tenant_full_name', ['full_name'], unique=False)
        batch_op.create_index('ix_tenant_phone', ['phone'], unique=False)

    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_unit_property_house_number', ['property_id', 'house_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_constraint('uq_unit_property_house_number', type_='unique')

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_index('ix_tenant_phone')
        batch_op.drop_index('ix_tenant_full_name')

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_index('ix_property_name')
        batch_op.drop_index('ix_property_location')

    with op.batch_alter_table('lease', schema=None) as batch_op:
        batch_op.drop_index('ix_lease_is_active')

    # ### end Alembic commands ###
