"""add tenants and leases

Revision ID: 7a170a131005
Revises: 2180c64bcb62
Create Date: 2026-01-23 17:53:06.270955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a170a131005'
down_revision = '2180c64bcb62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lease',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lease', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lease_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lease_unit_id'), ['unit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lease', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lease_unit_id'))
        batch_op.drop_index(batch_op.f('ix_lease_tenant_id'))

    op.drop_table('lease')
    op.drop_table('tenant')
    # ### end Alembic commands ###
