"""change in models

Revision ID: b6d6a1394d2b
Revises: 1a4a3f5bc162
Create Date: 2026-02-10 18:07:08.356108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6d6a1394d2b'
down_revision = '1a4a3f5bc162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('period', sa.String(length=7), nullable=False))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_water_readings_reading_at'))
        batch_op.drop_index(batch_op.f('ix_water_readings_tenant'))
        batch_op.drop_index(batch_op.f('ix_water_readings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_water_readings_unit'))
        batch_op.drop_index(batch_op.f('ix_water_readings_unit_reading_at'))
        batch_op.create_index(batch_op.f('ix_water_readings_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_water_readings_period'), ['period'], unique=False)
        batch_op.create_index('ix_water_readings_unit_period', ['unit_id', 'period'], unique=False)
        batch_op.create_unique_constraint('uq_water_reading_unit_period', ['unit_id', 'period'])
        batch_op.drop_constraint(batch_op.f('water_readings_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'])
        batch_op.drop_column('rate_per_unit')
        batch_op.drop_column('prev_reading_value')
        batch_op.drop_column('tenant_id')
        batch_op.drop_column('amount')
        batch_op.drop_column('usage_units')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage_units', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('prev_reading_value', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('rate_per_unit', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('water_readings_tenant_id_fkey'), 'tenant', ['tenant_id'], ['id'])
        batch_op.drop_constraint('uq_water_reading_unit_period', type_='unique')
        batch_op.drop_index('ix_water_readings_unit_period')
        batch_op.drop_index(batch_op.f('ix_water_readings_period'))
        batch_op.drop_index(batch_op.f('ix_water_readings_company_id'))
        batch_op.create_index(batch_op.f('ix_water_readings_unit_reading_at'), ['unit_id', 'reading_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_water_readings_unit'), ['unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_water_readings_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_water_readings_tenant'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_water_readings_reading_at'), ['reading_at'], unique=False)
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('period')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###
