"""empty message

Revision ID: cfdf86ddb3ef
Revises: 6a85e9e342f0
Create Date: 2025-12-15 18:06:18.755943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfdf86ddb3ef'
down_revision = '6a85e9e342f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposit', sa.Numeric(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_column('deposit')

    # ### end Alembic commands ###
