"""deposit fields, payment splits, move out settlement

Revision ID: da74a98e4c6a
Revises: f84befb93cef
Create Date: 2026-02-09 15:06:44.574113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da74a98e4c6a'
down_revision = 'f84befb93cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('move_out_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lease_id', sa.Integer(), nullable=False),
    sa.Column('kplc_token_debt', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('damages_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('other_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('deposit_used', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remaining_debt', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lease_id'], ['lease.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('move_out_settlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_move_out_settlements_lease_id'), ['lease_id'], unique=False)

    with op.batch_alter_table('lease', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposit_amount', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('deposit_held', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('deposit_used', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('deposit_refunded', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('moved_out_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('water_paid', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('garbage_paid', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('rent_paid', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('credit_after', sa.Numeric(precision=12, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('credit_after')
        batch_op.drop_column('balance_after')
        batch_op.drop_column('rent_paid')
        batch_op.drop_column('garbage_paid')
        batch_op.drop_column('water_paid')

    with op.batch_alter_table('lease', schema=None) as batch_op:
        batch_op.drop_column('moved_out_at')
        batch_op.drop_column('deposit_refunded')
        batch_op.drop_column('deposit_used')
        batch_op.drop_column('deposit_held')
        batch_op.drop_column('deposit_amount')

    with op.batch_alter_table('move_out_settlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_move_out_settlements_lease_id'))

    op.drop_table('move_out_settlements')
    # ### end Alembic commands ###
