"""add payments

Revision ID: f84befb93cef
Revises: 1ed9f01ccb63
Create Date: 2026-02-09 14:37:33.778836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f84befb93cef'
down_revision = '1ed9f01ccb63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('paid_for_month', sa.Date(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=True),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('ix_payment_paid_at', ['paid_at'], unique=False)
        batch_op.create_index('ix_payment_paid_for_month', ['paid_for_month'], unique=False)
        batch_op.create_index('ix_payment_tenant', ['tenant_id'], unique=False)
        batch_op.create_index('ix_payment_unit', ['unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_unit_id'), ['unit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_unit_id'))
        batch_op.drop_index(batch_op.f('ix_payments_tenant_id'))
        batch_op.drop_index('ix_payment_unit')
        batch_op.drop_index('ix_payment_tenant')
        batch_op.drop_index('ix_payment_paid_for_month')
        batch_op.drop_index('ix_payment_paid_at')

    op.drop_table('payments')
    # ### end Alembic commands ###
